# Generated by Django 5.0.9 on 2026-09-25 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CatalogueExamen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(max_length=30, unique=True)),
                ("libelle", models.CharField(max_length=200)),
                ("unite", models.CharField(blank=True, max_length=30)),
                (
                    "valeur_reference_min",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
                (
                    "valeur_reference_max",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=10, null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "examen du catalogue",
                "ordering": ["libelle"],
            },
        ),
        migrations.CreateModel(
            name="ResultatExamen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valeur", models.CharField(max_length=100)),
                ("unite", models.CharField(blank=True, max_length=30)),
                ("hors_reference", models.BooleanField(default=False)),
                (
                    "critique",
                    models.BooleanField(
                        default=False,
                        help_text="Déclenche l'alerte valeur critique (Should).",
                    ),
                ),
                ("valide_le", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "résultat d'examen",
            },
        ),
        migrations.CreateModel(
            name="ExamenLabo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("PRESCRIT", "Prescrit"),
                            ("PRELEVE", "Prélevé"),
                            ("VALIDE", "Validé"),
                        ],
                        default="PRESCRIT",
                        max_length=10,
                    ),
                ),
                ("demande_le", models.DateTimeField(auto_now_add=True)),
                (
                    "catalogue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="labo.catalogueexamen",
                    ),
                ),
            ],
            options={
                "verbose_name": "examen de laboratoire",
            },
        ),
    ]
