# Generated by Django 5.0.9 on 2026-09-25 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("labo", "0001_initial"),
        ("prescriptions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="examenlabo",
            name="ligne_prescription",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="examen_labo",
                to="prescriptions.ligneprescription",
            ),
        ),
        migrations.AddField(
            model_name="resultatexamen",
            name="examen",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resultat",
                to="labo.examenlabo",
            ),
        ),
        migrations.AddField(
            model_name="resultatexamen",
            name="valide_par",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddIndex(
            model_name="examenlabo",
            index=models.Index(fields=["statut"], name="idx_examen_statut"),
        ),
    ]
