# Generated by Django 5.0.9 on 2026-09-25 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EpisodeDeSoins",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.CharField(editable=False, max_length=30, unique=True),
                ),
                (
                    "type_episode",
                    models.CharField(
                        choices=[
                            ("AMBULATOIRE", "Ambulatoire"),
                            ("HOSPITALISATION", "Hospitalisation"),
                            ("URGENCE", "Urgence"),
                        ],
                        default="AMBULATOIRE",
                        max_length=20,
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[("OUVERT", "Ouvert"), ("CLOTURE", "Clôturé")],
                        default="OUVERT",
                        max_length=10,
                    ),
                ),
                ("date_ouverture", models.DateTimeField(auto_now_add=True)),
                ("date_fermeture", models.DateTimeField(blank=True, null=True)),
                (
                    "montant_du",
                    models.DecimalField(
                        decimal_places=2, default=0, editable=False, max_digits=12
                    ),
                ),
                (
                    "montant_paye",
                    models.DecimalField(
                        decimal_places=2, default=0, editable=False, max_digits=12
                    ),
                ),
                (
                    "ouvert_par",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="episodes",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "épisode de soins",
                "ordering": ["-date_ouverture"],
                "indexes": [
                    models.Index(
                        fields=["patient", "-date_ouverture"],
                        name="idx_episode_patient_date",
                    )
                ],
            },
        ),
    ]
