# Generated by Django 5.0.9 on 2026-09-25 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CorrespondanceGraphie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("graphie", models.CharField(db_index=True, max_length=100)),
                ("graphie_canonique", models.CharField(db_index=True, max_length=100)),
            ],
            options={
                "verbose_name": "correspondance de graphie",
                "unique_together": {("graphie", "graphie_canonique")},
            },
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ipp",
                    models.CharField(
                        db_index=True, editable=False, max_length=20, unique=True
                    ),
                ),
                ("annee_creation", models.PositiveSmallIntegerField(editable=False)),
                ("nom", models.CharField(max_length=100)),
                ("prenom", models.CharField(max_length=100)),
                ("date_naissance", models.DateField(blank=True, null=True)),
                (
                    "date_naissance_estimee",
                    models.BooleanField(
                        default=False,
                        help_text="Âge souvent estimé : cf. tolérance en détection de doublons.",
                    ),
                ),
                (
                    "sexe",
                    models.CharField(
                        choices=[
                            ("M", "Masculin"),
                            ("F", "Féminin"),
                            ("I", "Indéterminé"),
                        ],
                        default="I",
                        max_length=1,
                    ),
                ),
                (
                    "telephone",
                    models.CharField(blank=True, db_index=True, max_length=30),
                ),
                ("adresse", models.CharField(blank=True, max_length=255)),
                (
                    "cle_phonetique",
                    models.CharField(
                        blank=True, db_index=True, editable=False, max_length=32
                    ),
                ),
                ("actif", models.BooleanField(default=True)),
                ("cree_le", models.DateTimeField(auto_now_add=True)),
                (
                    "cree_par",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="patients_crees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fusionne_vers",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fiches_absorbees",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "patient",
            },
        ),
        migrations.CreateModel(
            name="FusionPatient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("effectuee_le", models.DateTimeField(auto_now_add=True)),
                ("annulee", models.BooleanField(default=False)),
                ("annulee_le", models.DateTimeField(blank=True, null=True)),
                (
                    "auteur",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient_absorbe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fusions_en_tant_qu_absorbe",
                        to="patients.patient",
                    ),
                ),
                (
                    "patient_cible",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fusions_en_tant_que_cible",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "fusion de patients",
                "ordering": ["-effectuee_le"],
            },
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(fields=["nom", "prenom"], name="idx_patient_nom_prenom"),
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(fields=["telephone"], name="idx_patient_telephone"),
        ),
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(fields=["cle_phonetique"], name="idx_patient_cle_phon"),
        ),
    ]
