# Generated by Django 5.0.9 on 2026-09-25 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("consultations", "0002_initial"),
        ("labo", "0001_initial"),
        ("pharmacie", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Prescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("EN_ATTENTE", "En attente"),
                            ("PARTIELLE", "Partiellement honorée"),
                            ("HONOREE", "Honorée"),
                            ("ANNULEE", "Annulée"),
                        ],
                        default="EN_ATTENTE",
                        max_length=15,
                    ),
                ),
                (
                    "consultation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescriptions",
                        to="consultations.consultation",
                    ),
                ),
                (
                    "prescripteur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "prescription",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="LignePrescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_ligne",
                    models.CharField(
                        choices=[
                            ("MEDICAMENT", "Médicament"),
                            ("EXAMEN", "Examen de laboratoire"),
                        ],
                        max_length=15,
                    ),
                ),
                ("libelle_produit", models.CharField(editable=False, max_length=200)),
                ("posologie", models.CharField(blank=True, max_length=200)),
                ("quantite", models.PositiveIntegerField(default=1)),
                ("honoree", models.BooleanField(default=False)),
                (
                    "examen",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="labo.catalogueexamen",
                    ),
                ),
                (
                    "medicament",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="pharmacie.medicament",
                    ),
                ),
                (
                    "prescription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes",
                        to="prescriptions.prescription",
                    ),
                ),
            ],
            options={
                "verbose_name": "ligne de prescription",
            },
        ),
        migrations.AddIndex(
            model_name="prescription",
            index=models.Index(
                condition=models.Q(("statut", "EN_ATTENTE")),
                fields=["statut"],
                name="idx_prescription_en_attente",
            ),
        ),
    ]
