# Generated by Django 5.0.9 on 2026-09-25 14:17

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="JournalAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("horodatage", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "entite",
                    models.CharField(
                        help_text="Nom du modèle concerné, ex. Patient", max_length=100
                    ),
                ),
                ("entite_id", models.CharField(max_length=64)),
                (
                    "action",
                    models.CharField(
                        help_text="creation, modification, fusion, annulation, ...",
                        max_length=50,
                    ),
                ),
                ("valeurs_avant", models.JSONField(blank=True, null=True)),
                ("valeurs_apres", models.JSONField(blank=True, null=True)),
                ("adresse_ip", models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "entrée de journal d'audit",
                "ordering": ["-horodatage"],
            },
        ),
        migrations.CreateModel(
            name="ParametreEtablissement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom_etablissement", models.CharField(max_length=200)),
                ("code_etablissement", models.CharField(max_length=3)),
                (
                    "fusion_reversibilite_jours",
                    models.PositiveIntegerField(
                        default=90,
                        help_text="Durée pendant laquelle une fusion de fiches patient reste réversible.",
                    ),
                ),
            ],
            options={
                "verbose_name": "paramètres de l'établissement",
            },
        ),
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=100, unique=True)),
                ("libelle", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name": "permission",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(unique=True)),
                ("libelle", models.CharField(max_length=100)),
                (
                    "acces_contenu_clinique",
                    models.BooleanField(
                        default=False,
                        help_text="Doit rester False pour le rôle administrateur système.",
                    ),
                ),
            ],
            options={
                "verbose_name": "rôle",
                "ordering": ["libelle"],
            },
        ),
        migrations.CreateModel(
            name="Utilisateur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("telephone", models.CharField(blank=True, max_length=30)),
                (
                    "echecs_authentification",
                    models.PositiveSmallIntegerField(default=0),
                ),
                ("verrouille_jusqu_a", models.DateTimeField(blank=True, null=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
            ],
            options={
                "verbose_name": "utilisateur",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
