# Generated by Django 5.0.9 on 2026-09-25 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("core", "0001_initial"),
        ("hospitalisation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="utilisateur",
            name="service_rattachement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="hospitalisation.service",
            ),
        ),
        migrations.AddField(
            model_name="utilisateur",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
        migrations.AddField(
            model_name="journalaudit",
            name="auteur",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="operations_journalisees",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="role",
            name="permissions",
            field=models.ManyToManyField(
                blank=True, related_name="roles", to="core.permission"
            ),
        ),
        migrations.AddField(
            model_name="utilisateur",
            name="roles",
            field=models.ManyToManyField(
                blank=True, related_name="utilisateurs", to="core.role"
            ),
        ),
        migrations.AddIndex(
            model_name="journalaudit",
            index=models.Index(
                fields=["entite", "entite_id"], name="core_journa_entite_ebc6ed_idx"
            ),
        ),
    ]
