# Generated by Django 5.0.9 on 2026-09-25 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("episodes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TarifActe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(max_length=30, unique=True)),
                ("libelle", models.CharField(max_length=200)),
                ("montant", models.DecimalField(decimal_places=2, max_digits=12)),
                ("actif", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "tarif d'acte",
                "ordering": ["libelle"],
            },
        ),
        migrations.CreateModel(
            name="JournalCaisse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_cloture", models.DateField(unique=True)),
                (
                    "montant_theorique",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "montant_compte",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "ecart",
                    models.DecimalField(
                        decimal_places=2, editable=False, max_digits=12
                    ),
                ),
                ("cloture_le", models.DateTimeField(auto_now_add=True)),
                (
                    "cloture_par",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "journal de caisse",
                "ordering": ["-date_cloture"],
            },
        ),
        migrations.CreateModel(
            name="ActeFacturable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantite", models.PositiveIntegerField(default=1)),
                (
                    "montant",
                    models.DecimalField(
                        decimal_places=2, editable=False, max_digits=12
                    ),
                ),
                ("exoneration", models.BooleanField(default=False)),
                ("motif_exoneration", models.CharField(blank=True, max_length=255)),
                ("facture_le", models.DateTimeField(auto_now_add=True)),
                (
                    "episode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="actes_factures",
                        to="episodes.episodedesoins",
                    ),
                ),
                (
                    "facture_par",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tarif",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="facturation.tarifacte",
                    ),
                ),
            ],
            options={
                "verbose_name": "acte facturable",
                "ordering": ["-facture_le"],
            },
        ),
        migrations.CreateModel(
            name="Paiement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("montant", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("ESPECES", "Espèces"),
                            ("MOBILE_MONEY", "Monnaie électronique"),
                            ("AUTRE", "Autre"),
                        ],
                        default="ESPECES",
                        max_length=15,
                    ),
                ),
                (
                    "numero_recu",
                    models.CharField(editable=False, max_length=30, unique=True),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "encaisse_par",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "episode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="paiements",
                        to="episodes.episodedesoins",
                    ),
                ),
            ],
            options={
                "verbose_name": "paiement",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["date", "encaisse_par"], name="idx_paiement_date_user"
                    )
                ],
            },
        ),
    ]
