# Generated by Django 5.0.9 on 2026-09-25 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("consultations", "0001_initial"),
        ("episodes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Lit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.CharField(max_length=20)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("LIBRE", "Libre"),
                            ("OCCUPE", "Occupé"),
                            ("HORS_SERVICE", "Hors service"),
                        ],
                        default="LIBRE",
                        max_length=15,
                    ),
                ),
            ],
            options={
                "verbose_name": "lit",
                "ordering": ["service", "numero"],
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(max_length=20, unique=True)),
                ("nom", models.CharField(max_length=100)),
                ("actif", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "service",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="Sejour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_admission", models.DateTimeField()),
                ("date_sortie", models.DateTimeField(blank=True, null=True)),
                (
                    "mode_sortie",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("GUERISON", "Guérison"),
                            ("MUTATION", "Mutation"),
                            ("EVASION", "Évasion"),
                            ("DECES", "Décès"),
                            ("SCAM", "Sortie contre avis médical"),
                            ("TRANSFERT", "Transfert"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "admis_par",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "diagnostic_sortie",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="consultations.diagnosticcim11",
                    ),
                ),
                (
                    "episode",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sejour",
                        to="episodes.episodedesoins",
                    ),
                ),
                (
                    "lit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sejours",
                        to="hospitalisation.lit",
                    ),
                ),
            ],
            options={
                "verbose_name": "séjour",
                "ordering": ["-date_admission"],
            },
        ),
        migrations.AddField(
            model_name="lit",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lits",
                to="hospitalisation.service",
            ),
        ),
        migrations.CreateModel(
            name="SoinQuotidien",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_heure", models.DateTimeField()),
                ("description", models.TextField()),
                (
                    "realise_par",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sejour",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="soins",
                        to="hospitalisation.sejour",
                    ),
                ),
            ],
            options={
                "verbose_name": "soin quotidien",
                "ordering": ["-date_heure"],
            },
        ),
        migrations.AlterUniqueTogether(
            name="lit",
            unique_together={("service", "numero")},
        ),
    ]
