# Generated by Django 5.0.9 on 2026-09-25 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Allergie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("libelle", models.CharField(max_length=200)),
                (
                    "severite",
                    models.CharField(
                        choices=[
                            ("LEGERE", "Légère"),
                            ("MODEREE", "Modérée"),
                            ("SEVERE", "Sévère"),
                        ],
                        default="MODEREE",
                        max_length=10,
                    ),
                ),
                ("signalee_le", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "allergie",
            },
        ),
        migrations.CreateModel(
            name="Consultation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "temperature_c",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                (
                    "tension_arterielle_systolique",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "tension_arterielle_diastolique",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "frequence_cardiaque",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "frequence_respiratoire",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "poids_kg",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                ("motif", models.CharField(max_length=255)),
                ("anamnese", models.TextField(blank=True)),
                ("examen_clinique", models.TextField(blank=True)),
                ("conclusion", models.TextField(blank=True)),
                (
                    "modele_utilise",
                    models.CharField(
                        blank=True,
                        help_text="Modèle de consultation par motif fréquent (Should).",
                        max_length=100,
                    ),
                ),
            ],
            options={
                "verbose_name": "consultation",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Diagnostic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("principal", models.BooleanField(default=True)),
                ("commentaire", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "verbose_name": "diagnostic",
            },
        ),
        migrations.CreateModel(
            name="DiagnosticCIM11",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, unique=True)),
                ("libelle", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "diagnostic CIM-11",
                "ordering": ["code"],
            },
        ),
    ]
