# Generated by Django 5.0.9 on 2026-09-25 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("consultations", "0001_initial"),
        ("episodes", "0001_initial"),
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="allergie",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="allergies",
                to="patients.patient",
            ),
        ),
        migrations.AddField(
            model_name="consultation",
            name="episode",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consultations",
                to="episodes.episodedesoins",
            ),
        ),
        migrations.AddField(
            model_name="consultation",
            name="medecin",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="consultations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="diagnostic",
            name="consultation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="diagnostics",
                to="consultations.consultation",
            ),
        ),
        migrations.AddField(
            model_name="diagnostic",
            name="code_cim11",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="consultations.diagnosticcim11",
            ),
        ),
        migrations.AddIndex(
            model_name="consultation",
            index=models.Index(
                fields=["episode", "-date"], name="idx_consult_episode_date"
            ),
        ),
    ]
