# Generated by Django 5.0.9 on 2026-09-25 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Medicament",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(max_length=30, unique=True)),
                (
                    "denomination_commune",
                    models.CharField(help_text="DCI", max_length=200),
                ),
                ("nom", models.CharField(max_length=200)),
                ("forme", models.CharField(blank=True, max_length=100)),
                ("dosage", models.CharField(blank=True, max_length=50)),
                ("seuil_alerte", models.PositiveIntegerField(default=10)),
                ("stock_courant", models.IntegerField(default=0, editable=False)),
            ],
            options={
                "verbose_name": "médicament",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="MouvementStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_mouvement",
                    models.CharField(
                        choices=[
                            ("ENTREE", "Entrée"),
                            ("SORTIE", "Sortie (dispensation)"),
                            ("AJUSTEMENT", "Ajustement d'inventaire"),
                            ("PEREMPTION", "Retrait pour péremption"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "quantite",
                    models.IntegerField(
                        help_text="Positif en entrée, négatif en sortie."
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("motif", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "verbose_name": "mouvement de stock",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="LotPharmaceutique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_lot", models.CharField(max_length=50)),
                ("date_peremption", models.DateField(db_index=True)),
                ("quantite_initiale", models.PositiveIntegerField()),
                ("quantite_restante", models.IntegerField()),
                ("fournisseur", models.CharField(blank=True, max_length=200)),
                ("recu_le", models.DateTimeField(auto_now_add=True)),
                (
                    "medicament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lots",
                        to="pharmacie.medicament",
                    ),
                ),
            ],
            options={
                "verbose_name": "lot pharmaceutique",
                "ordering": ["date_peremption"],
            },
        ),
    ]
