# Generated by Django 5.0.9 on 2026-09-25 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pharmacie", "0001_initial"),
        ("prescriptions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="mouvementstock",
            name="ligne_prescription",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="prescriptions.ligneprescription",
            ),
        ),
        migrations.AddField(
            model_name="mouvementstock",
            name="lot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="mouvements",
                to="pharmacie.lotpharmaceutique",
            ),
        ),
        migrations.AddField(
            model_name="mouvementstock",
            name="utilisateur",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="lotpharmaceutique",
            unique_together={("medicament", "numero_lot")},
        ),
        migrations.AddIndex(
            model_name="mouvementstock",
            index=models.Index(fields=["lot", "date"], name="idx_mouvement_lot_date"),
        ),
    ]
